### ISSUE TITLE
Complition error while installing under Mojolicious 6.05

### ISSUE THREAD

**Issue by zisten** [abhishekisnot/Mojolicious-Plugin-REST#5]
In Mojolicious 6.05:

```
Can't locate object method "bridge" via package "Mojolicious::Routes" at lib/Mojolicious/Plugin/REST.pm line 114.
```

Could you fix it?

**Comment by abhishekisnot** [comment]
I'm not actively maintaining this repo. However, if you submit a pull request, I'll merge it as soon as possible.

**Comment by zisten** [comment]
@abhishekisnot , seems you haven't upgrade the package in CPAN
